### ISSUE TITLE
jmp hook

### ISSUE THREAD

**Issue by aFakeCmd** [urShadow/urmem#2]
Привет! С чем связанно неправильное возвращение оригинальной функции при jmp, после вызова функции он кидает себя в бесконечный цикл 
`return urmem::call_function<urmem::calling_convention::thiscall, char, void*, char*>(hkSub.get_original_addr(), ecx, a2);`
![16K1r6v](https://user-images.githubusercontent.com/60480464/109737508-c27cd980-7bf8-11eb-82d4-c283b3dc9784.png)

**Comment by katursis** [comment]
Покажи весь код хука, скорее всего ты забываешь его отключать перед вызовом оригинала.

Лучше вызывай так: 
```cpp
hkSub.call<urmem::calling_convention::thiscall, char>(ecx, a2);
```

**Comment by aFakeCmd** [comment]
`char __fastcall HOOK(void *EDX, void *ecx, char *a2)`
`{`
`    return urmem::call_function<urmem::calling_convention::thiscall, char, void*, char*>(hkSub.get_original_addr(), ecx, a2);`
`}`

`hkSub.install(0x483990, urmem::get_func_addr(&HOOK), urmem::hook::type::jmp, 6) `
